name: Production

on: 
  push:
    branches:
      - master

jobs:

  Build_and_Run:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1

    - name: Build the Terraform docker image
      run: docker build . --file Dockerfile --tag ignw/dc-2020-aci-terraform:latest

    - name: Validate the terraform config
      run: docker run ignw/dc-2020-aci-terraform:latest terraform validate

    - name: Apply the terraform config
      run: docker run ignw/dc-2020-aci-terraform:latest terraform apply -auto-approve -parallelism=1